name: "Comprueba Ortografía"

on:
  push:
    paths:
      - 'README.md'
      - '**/*.md'
      - 'doc/words.dic'
      - 'words.dic'

  pull_request:
    paths:
      - 'README.md'
      - '**/*.md'
      - 'doc/words.dic'
      - 'words.dic'

jobs:
  Ortografia:
    runs-on: ubuntu-latest

    steps:
      - name: Prerrequisites
        run: |
          sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y libtext-hunspell-perl autopoint
      - uses: actions/checkout@v4
      - name: Usa install-with-cpm
        uses: perl-actions/install-with-cpm@stable
        with:
          install: |
            Test::Text
            TAP::Harness
          sudo: true
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: "Install the linter"
        run: bundle install
      - name: Comprueba la ortografía
        run: rake spellcheck --trace

