name: "Lint Markdown"

on:
  push:
    paths:
      - '**/*.md'
      - ".mdl.rb"

  pull_request:
    paths:
      - '**/*.md'
      - ".mdl.rb"

jobs:
  LintMarkdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: "Install the linter"
        run: bundle install
      - name: "Comprueba estilo de archivos Markdown"
        run: rake mdlint --trace

