name: "Lint Markdown"

on:
  push:
    paths:
      - '**/*.md'

  pull_request:
    paths:
      - '**/*.md'

jobs:
  LintMarkdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: "Install the linter"
        run: gem install mdl
      - name: "Comprueba estilo de archivos Markdown"
        working-directory: ${{ github.workspace }}
        run: mdl --ignore-front-matter --style .mdl.rb .

